# Generated by Django 5.2 on 2026-05-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetaf',
            old_name='favoritos',
            new_name='favorito',
        ),
        migrations.AlterUniqueTogether(
            name='recetaf',
            unique_together={('favorito', 'recetas')},
        ),
    ]
